### ISSUE TITLE
Issue: Missing id_token

### ISSUE THREAD

**Issue by Venkateswarlujinkala17** [mattermost/mattermost-plugin-skype4business#13]
Hi All,

 Thank you for the plugin. We installed the plugin and enabled in Mattermost and registered application in Azure as described. We can see the icon displayed in Mattermost but when i clicked the icon nothing is happening. But in the background i see the redirect url returning **"missing id_token"** response with http status code **401**.

Could you please let me know what i can be missing in the configuration.

Here is my Manifest file from Azure

{
	"id": "badbb555-f750-49f6-952e-281b6d4efdee",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": 2,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "bXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2019-07-17T11:08:06Z",
	"groupMembershipClaims": null,
	"identifierUris": [],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "Mattermost Skype for Business Plugin - XXXX",
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": true,
	"oauth2Permissions": [],
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [],
	"preAuthorizedApplications": [],
	"publisherDomain": "XXXXXXXX.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "https://XXXXXXXXXXX/plugins/skype4business/api/v1/auth_redirect",
			"type": "Web"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000004-0000-0ff1-ce00-000000000000",
			"resourceAccess": [
				{
					"id": "d0c8f2ea-8f80-4289-8e78-4bc821cde1bc",
					"type": "Scope"
				}
			]
		},
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADandPersonalMicrosoftAccount",
	"tags": [],
	"tokenEncryptionKeyId": null
}

Thanks,
Venkat

**Comment by kosgrz** [comment]
Hi @Venkateswarlujinkala17 ! Your manifest looks ok. Could you tell me what web browser and operating system do you use? Maybe your browser is blocking pop-ups on your MM page?

**Comment by Venkateswarlujinkala17** [comment]
Hi @kosgrz ,

 Thank you for your response. My system configuration is as below.

  OS: Windows 10
 Browser: Chrome version 75.0.3770.142 (Official Build) (64-bit)

I have allowed pops ups but still i am getting the same error.

Thanks,
Venkat

**Comment by kosgrz** [comment]
@Venkateswarlujinkala17 thank you for very helpful information. I was able to recreate the bug on my local machine and now I'm working on a fix. I think, I will finish it until the end of the week :+1:

**Comment by Venkateswarlujinkala17** [comment]
Hi @kosgrz ,

 Thank you for the update. I will wait for the fix.

Thanks,
Venkat

**Comment by kosgrz** [comment]
Hi @Venkateswarlujinkala17 ,
Could you tell me what version of MM do you use?
Could you also send me logs from your browser console when you are trying to create a meeting?

**Comment by hanzei** [comment]
@Venkateswarlujinkala17 Are you still encountering this issue?

**Comment by hanzei** [comment]
Closing this issue due to it's age
