### ISSUE TITLE
Migrate logging to use RPC Logging methods

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-skype4business#32]
Instead of using `mlog` all log calls should use the RPC methods `LogX`, e.g. [`LogDebug`](https://developers.mattermost.com/extend/plugins/server/reference/#API.LogDebug). This allows the server to gradually select which log messages to show in the server logs.

**Comment by kosgrz** [comment]
I'd like to do it :)

**Comment by hanzei** [comment]
I was hoping for this :wink:
