### ISSUE TITLE
How to fix 'Server Domain'?

### ISSUE THREAD

**Issue by rhd** [mattermost/mattermost-plugin-skype4business#34]
Hi, I was flailing with the `Server Domain` setting and stuck in a `https://theedge.company.com` and I can't change it. It seems since it was valid, the plugin stuck it in the kv store. Can you tell me now to clear out the settings so I can stick in the correct information?

Thanks!

**Comment by rhd** [comment]
Hi, thanks for taking note of this. I'd love it if you could tell me a way to bandaid over this? How can I call `KVDeleteAll()` (or equivalent) to blow away all my changes?

**Comment by kosgrz** [comment]
Hi @rhd ! Thank you for raising this issue. I think It's not possible now to delete this record in the kv store, but we can fix it and make a new release of the plugin, so you will be able to use it soon :+1:

**Comment by rhd** [comment]
Looking forward to the new release! If you'd like to me test a beta build or something, let me know. The current situation is making this more and more important.

Thanks!
