### ISSUE TITLE
error loading module requirements

### ISSUE THREAD

**Issue by jimbosiljevac** [mattermost/mattermost-plugin-skype4business#38]
Getting the following error when trying to build:

go: willnorris.com/go/imageproxy@v0.9.0: unrecognized import path "willnorris.com/go/imageproxy" (https fetch: Get https://willnorris.com/go/imageproxy?go-get=1: x509: certificate signed by unknown authority)
go: error loading module requirements

**Comment by hanzei** [comment]
@jimbosiljevac What go version are you using? Can you confirm that you are using the latest `master`?

**Comment by jimbosiljevac** [comment]
I think I was able to resolve. Thank you.
