### ISSUE TITLE
"Unable to generate plugin webapp bundle." when uploading plugin to mattermost

### ISSUE THREAD

**Issue by yoandrygc** [mattermost/mattermost-plugin-skype4business#52]

**Comment by hanzei** [comment]
@yoandrygc What commands did you exactly run to get to this error?

**Comment by yoandrygc** [comment]
None, I just tried to upload it to a mattermost server.

**Comment by hanzei** [comment]
@yoandrygc Do you see any error in the server logs?

**Comment by hanzei** [comment]
@yoandrygc Did upload https://github.com/mattermost/mattermost-plugin-skype4business/releases/tag/v0.1.2 ?

**Comment by larkox** [comment]
@yoandrygc Is this issue solved?
